apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxTemplate
metadata:
  name: code-execution-template-kata-sa
  namespace: llm-sandbox-demo
spec:
  envVarsInjectionPolicy: Allowed
  networkPolicyManagement: Managed
  podTemplate:
    metadata:
      labels:
        app: code-sandbox
        runtime: kata
        demo: security
    spec:
      serviceAccountName: sandbox-demo-sa
      automountServiceAccountToken: true
      runtimeClassName: kata-remote
      containers:
      - image: quay.io/eesposit/python-runtime-sandbox:latest
        name: sandbox
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
  service: true
