apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: code-sandbox-pool-kata-sa
  namespace: llm-sandbox-demo
spec:
  replicas: 2
  sandboxTemplateRef:
    name: code-execution-template-kata-sa
  updateStrategy:
    type: OnReplenish
