apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: code-llm
  namespace: llm-sandbox-demo
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    openshift.io/display-name: "Code LLM"
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      storageUri: hf://ibm-granite/granite-3.1-2b-instruct
    minReplicas: 1
    maxReplicas: 1
